# Generated by Django 3.1.5 on 2021-01-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_address_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='profiles.userprofile'),
        ),
    ]
