# Generated by Django 3.1.5 on 2021-01-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210109_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
