# Generated by Django 3.1.5 on 2021-01-16 15:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210111_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='UK', max_length=2),
        ),
    ]
