# Generated by Django 3.1.5 on 2021-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20201231_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
