# Generated by Django 3.1.5 on 2021-02-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_regioncountry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionCountry',
        ),
    ]
