# Generated by Django 3.1.5 on 2021-02-27 15:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_delete_regioncountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
        ),
    ]
