# Generated by Django 3.1.5 on 2021-03-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_number', models.CharField(editable=False, max_length=32)),
                ('user_email', models.CharField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
