# Generated by Django 3.1.5 on 2021-03-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
